import type { Config } from "tailwindcss";

// Design tokens ported verbatim from the Stitch reference mockups
// (D:\Lokesh\study-planner-stitch-ref\month-view.html <script id="tailwind-config">)
const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#9f9d9a",
        "surface-container": "#efeeeb",
        "inverse-surface": "#2f312f",
        "tertiary-fixed-dim": "#c8c6c3",
        "on-surface": "#1b1c1a",
        "on-tertiary-fixed": "#1b1c1a",
        "surface-dim": "#dbdad7",
        "surface-container-lowest": "#ffffff",
        tertiary: "#1f201e",
        outline: "#7a776e",
        "surface-container-high": "#e9e8e5",
        "tertiary-container": "#353533",
        "on-secondary-fixed-variant": "#474744",
        "on-primary-fixed-variant": "#494740",
        "on-error": "#ffffff",
        "on-primary-fixed": "#1d1c16",
        "inverse-primary": "#cbc6bd",
        "on-secondary-container": "#636360",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-container": "#37352f",
        "secondary-fixed-dim": "#c8c6c3",
        "tertiary-fixed": "#e4e2df",
        "surface-container-low": "#f4f3f0",
        "surface-tint": "#615e57",
        "on-primary": "#ffffff",
        "primary-fixed": "#e7e2d9",
        "outline-variant": "#cbc6bc",
        error: "#ba1a1a",
        "surface-bright": "#faf9f6",
        "secondary-container": "#e2dfdb",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f2f1ee",
        "on-background": "#1b1c1a",
        primary: "#21201a",
        "on-secondary-fixed": "#1b1c1a",
        "surface-container-highest": "#e3e2df",
        "on-tertiary-fixed-variant": "#474744",
        "on-secondary": "#ffffff",
        "surface-variant": "#e3e2df",
        secondary: "#5f5e5c",
        "on-primary-container": "#a19d95",
        "primary-fixed-dim": "#cbc6bd",
        background: "#faf9f6",
        surface: "#faf9f6",
        "on-surface-variant": "#49473f",
        "secondary-fixed": "#e5e2de",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-lg": "1.25rem",
        "space-md": "0.75rem",
        gutter: "1rem",
        "space-xs": "0.25rem",
        "gutter-mobile": "0.75rem",
        "space-sm": "0.5rem",
        margin: "2rem",
        "margin-mobile": "1rem",
        "space-xl": "2rem",
      },
      fontFamily: {
        "body-md": ["var(--font-inter)"],
        "headline-md": ["var(--font-inter)"],
        "headline-xl": ["var(--font-inter)"],
        code: ["JetBrains Mono", "monospace"],
        "headline-lg": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
        "headline-sm": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "headline-xl-mobile": ["var(--font-inter)"],
        "label-md": ["var(--font-inter)"],
        "body-sm": ["var(--font-inter)"],
      },
      fontSize: {
        "body-md": [
          "14px",
          { lineHeight: "22px", letterSpacing: "-0.006em", fontWeight: "400" },
        ],
        "headline-md": [
          "19px",
          { lineHeight: "26px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "headline-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        code: ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": [
          "26px",
          { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "22px",
          { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "headline-sm": [
          "15px",
          { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-lg": [
          "16px",
          { lineHeight: "26px", letterSpacing: "-0.011em", fontWeight: "400" },
        ],
        "headline-xl-mobile": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.025em", fontWeight: "700" },
        ],
        "label-md": [
          "13px",
          { lineHeight: "18px", letterSpacing: "-0.005em", fontWeight: "500" },
        ],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
